import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
 
    {
      _id: uuid(),
      name: "Backpack",
      categoryName: "Best Sellers",
      price: 2500,
      image: "https://n4.sdlcdn.com/imgs/a/7/i/Wildcraft-Orange-Backpack-SDL259448697-1-4c0f9.jpg",
      deliveryTime: false,
      inStock: true,
      brand: "Osprey",
      originalPrice: 3200,
      count: 1,
      wish: false,
      percentage:"21.87",
      star: "4.5"
    },
    {
      _id: uuid(),
      name: "Sleeping Bag",
      categoryName: " Branded Products",
      price: 3000,
      image: "https://images.sg.content-cdn.io/cdn/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/WCTVLTSPBGL.jpg",
      deliveryTime: false,
      inStock: true,
      brand: "Marmot",
      originalPrice: 4200,
      count: 1,
      wish: false,
      percentage:"28.58",
      star: "4.3"
    },
    {
      _id: uuid(),
      name: "Tent",
      categoryName: " Branded Products",
      price: 1100,
      image: "https://th.bing.com/th/id/OIP.3XKJj_jukEMsT-rGL4ILNQAAAA?w=184&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: false,
      inStock: false,
      brand: "North Face",
      originalPrice: 2200,
      count: 1,
      wish: false,
      percentage:"50",
      star: "4.8"
    },
    {
      _id: uuid(),
      name: "Hiking Boots",
      categoryName: "Best Sellers",
      price: 3000,
      image: "https://th.bing.com/th/id/OIP.0JCIkcU5VhKzwmwbzfjkZgHaGZ?w=250&h=216&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: true,
      inStock: true,
      brand: "Merrell",
      originalPrice: 4500,
      count: 1,
      wish: false,
      percentage:"44.44",
      star: "4.2"
    },
    {
      _id: uuid(),
      name: "Water Bottle",
      categoryName: " Personalized designs",
      price: 350,
      image: "https://th.bing.com/th/id/OIP.iI3d4EMja0Kwq4pK-QVgjgHaIq?w=195&h=228&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: true,
      inStock: true,
      brand: "Nalgene",
      originalPrice: 350,
      count: 1,
      wish: false,
      percentage:"28.58",
      star: "3.9"
    },
    {
      _id: uuid(),
      name: "Sunglasses",
      categoryName: " Branded Products",
      price: 2100,
      image: "https://th.bing.com/th/id/OIP._Jz2HltQ9EoI800mpOCvIwHaHa?w=188&h=188&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: true,
      inStock: false,
      brand: "Ray-Ban",
      originalPrice: 2400,
      count: 1,
      wish: false,
      percentage:"44.44",
      star: "4.2"
    },
    {
      _id: uuid(),
      name: "Hat",
      categoryName: " Personalized designs",
      price: 450,
      image: "https://th.bing.com/th/id/OIP.7mp4_G1ozrnHQn2Dg9RyJwHaHa?w=198&h=198&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: true,
      inStock: true,
      brand: "New Era",
      originalPrice: 750,
      count: 1,
      wish: false,
      percentage:"40",
      star: "3.5"
    },
    {
      _id: uuid(),
      name: "Travel Umbrella",
      categoryName: " Personalized designs",
      price: 220,
      image: "https://th.bing.com/th/id/OIP.SanH6rbr9GC274qYxayxLwHaHa?w=173&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: true,
      inStock: false,
      brand: "ShedRain",
      originalPrice: 470,
      count: 1,
      wish: false,
      percentage:"63.73",
      star: "3.7"
    },
    {
      _id: uuid(),
      name: "Power Bank",
      categoryName: "Best Sellers",
      price: 2250,
      image: "https://th.bing.com/th/id/OIP._FX9kxCtF7qgZYdKoPg8VgHaFj?w=215&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: true,
      inStock: true,
      brand: "Anker",
      originalPrice: 3270,
      count: 1,
      wish: false,
      percentage:"31.20",
      star: "4.8"
    },
    {
      _id: uuid(),
      name: "Travel Guidebook",
      categoryName: " Personalized designs",
      price: 520,
      image: "https://th.bing.com/th/id/OIP.DyA3MY15BhIZd_W7P_kJegAAAA?w=195&h=253&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: true,
      inStock: true,
      brand: "Lonely Planet",
      originalPrice: 930,
      count: 1,
      wish: false,
      percentage:"44.10",
      star: "4.3"
    },
    {
      _id: uuid(),
      name: "Toiletries Bag",
      categoryName: "Best Sellers",
      price: 1620,
      image: "https://th.bing.com/th/id/OIP.IEVfI-t0dHqzIDcxdvyO-wHaHa?w=196&h=196&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: false,
      inStock: true,
      brand: "Herschel Supply Co.",
      originalPrice: 1800,
      count: 1,
      wish: false,
      percentage:"65.20",
      star: "4.5"
    },
    {
      _id: uuid(),
      name: "Lock",
      categoryName: " Personalized designs",
      price: 610,
      image: "https://th.bing.com/th/id/OIP.92yQdSdng0WGe3EYObLarAHaHa?w=195&h=195&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: false,
      inStock: false,
      brand: "Master Lock",
      originalPrice: 760,
      count: 1,
      wish: false,
      percentage:"32.70",
      star: "4.1"
    },
    {
      _id: uuid(),
      name: "First Aid Kit",
      categoryName: "Best Sellers",
      price: 2220,
      image: "https://th.bing.com/th/id/OIP.vvMZlnpORR2s0MsXu6uMFAHaHa?w=186&h=186&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: true,
      inStock: true,
      brand: "Braun",
      originalPrice: 2800,
      count: 1,
      wish: false,
      percentage:"44.44",
      star: "4.5"
    },
    {
      _id: uuid(),
      name: "Sunglasses Case",
      categoryName: " Personalized designs",
      price: 350,
      image: "https://th.bing.com/th/id/OIP.xyVEbN2jZDA-p-aUblSGlAHaHa?w=161&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: false,
      inStock: true,
      brand: "Oakley",
      originalPrice: 550,
      count: 1,
      wish: false,
      percentage:"68.67",
      star: "3.8"
    },
    {
      _id: uuid(),
      name: "Waterproof Phone Case",
      categoryName: " Personalized designs",
      price: 520,
      image: "https://th.bing.com/th/id/OIP.7ib4B11DmDVlPl4kDxwVZQAAAA?w=128&h=176&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: true,
      inStock: true,
      brand: "LifeProof",
      originalPrice: 780,
      count: 1,
      wish: false,
      percentage:"44.44",
      star: "3.6"
    },
    {
      _id: uuid(),
      name: "Travel Adapter",
      categoryName: " Branded Products",
      price: 1520,
      image: "https://th.bing.com/th/id/OIP.vYC69GXNGDyUUcp4XbVKUwHaHk?w=225&h=220&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: true,
      inStock: false,
      brand: "Anker",
      originalPrice: 1650,
      count: 1,
      wish: false,
      percentage:"20",
      star: "4.7"
    },
    {
      _id: uuid(),
      name: "Luggage Scale",
      categoryName: " Branded Products",
      price: 1410,
      image: "https://th.bing.com/th/id/OIP.UjHYiHrgzUGbXFCtsh_6EwHaHa?w=184&h=184&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: true,
      inStock: true,
      brand: "Etekcity",
      originalPrice: 1760,
      count: 1,
      wish: false,
      percentage:"46.10",
      star: "3.0"
    },
    {
      _id: uuid(),
      name: "Packing Cubes",
      categoryName: " Personalized designs",
      price: 720,
      image: "https://th.bing.com/th/id/OIP.-rU_ABDCwvTfDCXwJshBEAHaHa?w=144&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: true,
      inStock: true,
      brand: "Eagle Creek",
      originalPrice: 930,
      count: 1,
      wish: false,
      percentage:"25.59",
      star: "2.5"
    },
    {
      _id: uuid(),
      name: "Packing List",
      categoryName: " Personalized designs",
      price: 500,
      image: "https://th.bing.com/th/id/OIP.Ihecqcbmg8YL605FuugwHAHaKe?w=195&h=276&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: false,
      inStock: false,
      brand: "No Brand",
      originalPrice: 730,
      count: 1,
      wish: false,
      percentage:"61.54",
      star: "2.5"
    },
    {
      _id: uuid(),
      name: "Travel Journal",
      categoryNameName: " Personalized designs",
      price: 350,
      image: "https://th.bing.com/th/id/OIP.PEeKjo8UvG3KmsgpHrV82wHaHa?w=177&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: false,
      inStock: true,
      brand: "Leuchtturm1917",
      originalPrice: 480,
      count: 1,
      wish: false,
      percentage:"31.19",
      star: "2.5"

    },
];
