import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
 
    {
      _id: uuid(),
      name: "Backpack",
      categoryName: "Best Sellers",
      price: 2500,
      image: "https://n4.sdlcdn.com/imgs/a/7/i/Wildcraft-Orange-Backpack-SDL259448697-1-4c0f9.jpg",
      deliveryTime: false,
      inStock: true,
      brand: "Osprey",
    },
    {
      _id: uuid(),
      name: "Sleeping Bag",
      categoryName: " Branded Products",
      price: 3000,
      image: "https://images.sg.content-cdn.io/cdn/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/WCTVLTSPBGL.jpg",
      deliveryTime: false,
      inStock: true,
      brand: "Marmot",
    },
    {
      _id: uuid(),
      name: "Tent",
      categoryName: " Branded Products",
      price: 1100,
      image: "https://th.bing.com/th/id/OIP.3XKJj_jukEMsT-rGL4ILNQAAAA?w=184&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: false,
      inStock: false,
      brand: "North Face",
    },
    {
      _id: uuid(),
      name: "Hiking Boots",
      categoryName: "Best Sellers",
      price: 3000,
      image: "https://th.bing.com/th/id/OIP.0JCIkcU5VhKzwmwbzfjkZgHaGZ?w=250&h=216&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: true,
      inStock: true,
      brand: "Merrell",
    },
    {
      _id: uuid(),
      name: "Water Bottle",
      categoryName: " Personalized designs",
      price: 250,
      image: "https://th.bing.com/th/id/OIP.iI3d4EMja0Kwq4pK-QVgjgHaIq?w=195&h=228&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: true,
      inStock: true,
      brand: "Nalgene",
    },
    {
      _id: uuid(),
      name: "Sunglasses",
      categoryName: " Branded Products",
      price: 800,
      image: "https://th.bing.com/th/id/OIP._Jz2HltQ9EoI800mpOCvIwHaHa?w=188&h=188&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: true,
      inStock: false,
      brand: "Ray-Ban",
    },
    {
      _id: uuid(),
      name: "Hat",
      categoryName: " Personalized designs",
      price: 450,
      image: "https://th.bing.com/th/id/OIP.7mp4_G1ozrnHQn2Dg9RyJwHaHa?w=198&h=198&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: true,
      inStock: true,
      brand: "New Era",
    },
    {
      _id: uuid(),
      name: "Travel Umbrella",
      categoryName: " Personalized designs",
      price: 220,
      image: "https://th.bing.com/th/id/OIP.SanH6rbr9GC274qYxayxLwHaHa?w=173&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: true,
      inStock: false,
      brand: "ShedRain",
    },
    {
      _id: uuid(),
      name: "Power Bank",
      categoryName: "Best Sellers",
      price: 2250,
      image: "https://th.bing.com/th/id/OIP._FX9kxCtF7qgZYdKoPg8VgHaFj?w=215&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: true,
      inStock: true,
      brand: "Anker",
    },
    {
      _id: uuid(),
      name: "Travel Guidebook",
      categoryName: " Personalized designs",
      price: 520,
      image: "https://th.bing.com/th/id/OIP.DyA3MY15BhIZd_W7P_kJegAAAA?w=195&h=253&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: true,
      inStock: true,
      brand: "Lonely Planet",
    },
    {
      _id: uuid(),
      name: "Toiletries Bag",
      categoryName: "Best Sellers",
      price: 620,
      image: "https://th.bing.com/th/id/OIP.IEVfI-t0dHqzIDcxdvyO-wHaHa?w=196&h=196&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: false,
      inStock: true,
      brand: "Herschel Supply Co.",
    },
    {
      _id: uuid(),
      name: "Lock",
      categoryName: " Personalized designs",
      price: 310,
      image: "https://th.bing.com/th/id/OIP.92yQdSdng0WGe3EYObLarAHaHa?w=195&h=195&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: false,
      inStock: false,
      brand: "Master Lock",
    },
    {
      _id: uuid(),
      name: "First Aid Kit",
      categoryName: "Best Sellers",
      price: 1220,
      image: "https://th.bing.com/th/id/OIP.vvMZlnpORR2s0MsXu6uMFAHaHa?w=186&h=186&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: true,
      inStock: true,
      brand: "Braun",
    },
    {
      _id: uuid(),
      name: "Sunglasses Case",
      categoryName: " Personalized designs",
      price: 110,
      image: "https://th.bing.com/th/id/OIP.xyVEbN2jZDA-p-aUblSGlAHaHa?w=161&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: false,
      inStock: true,
      brand: "Oakley",
    },
    {
      _id: uuid(),
      name: "Waterproof Phone Case",
      categoryName: " Personalized designs",
      price: 120,
      image: "https://th.bing.com/th/id/OIP.7ib4B11DmDVlPl4kDxwVZQAAAA?w=128&h=176&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: true,
      inStock: true,
      brand: "LifeProof",
    },
    {
      _id: uuid(),
      name: "Travel Adapter",
      categoryName: " Branded Products",
      price: 520,
      image: "https://th.bing.com/th/id/OIP.vYC69GXNGDyUUcp4XbVKUwHaHk?w=225&h=220&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: true,
      inStock: false,
      brand: "Anker",
    },
    {
      _id: uuid(),
      name: "Luggage Scale",
      categoryName: " Branded Products",
      price: 410,
      image: "https://th.bing.com/th/id/OIP.UjHYiHrgzUGbXFCtsh_6EwHaHa?w=184&h=184&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: true,
      inStock: true,
      brand: "Etekcity",
    },
    {
      _id: uuid(),
      name: "Packing Cubes",
      categoryName: " Personalized designs",
      price: 320,
      image: "https://th.bing.com/th/id/OIP.-rU_ABDCwvTfDCXwJshBEAHaHa?w=144&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: true,
      inStock: true,
      brand: "Eagle Creek",
    },
    {
      _id: uuid(),
      name: "Packing List",
      categoryName: " Personalized designs",
      price: 50,
      image: "https://th.bing.com/th/id/OIP.Ihecqcbmg8YL605FuugwHAHaKe?w=195&h=276&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: false,
      inStock: false,
      brand: "No Brand",
    },
    {
      _id: uuid(),
      name: "Travel Journal",
      categoryNameName: " Personalized designs",
      price: 150,
      image: "https://th.bing.com/th/id/OIP.PEeKjo8UvG3KmsgpHrV82wHaHa?w=177&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      deliveryTime: false,
      inStock: true,
      brand: "Leuchtturm1917",
    },
  
    
    
  
    

  
];
